name: Build and deploy bundle
on:
  create:
    tags: '*'

jobs:
  package:
    name: Build and deploy bundle to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Upload bundle to S3
      run: |
        aws s3 cp ./build/* s3://origin-player-releases/${{ steps.get_version.outputs.VERSION }}/build/ --recursive